# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'StudentList_18.11' do
 
pod 'AFNetworking', '~> 2.0'

  # Pods for StudentList_18.11

end
